# Generated by Django 6.0.4 on 2026-04-22 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('domain', models.CharField(choices=[('informatique', 'Informatique'), ('mathematiques', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('economie', 'Économie'), ('autre', 'Autre')], default='informatique', max_length=50, verbose_name='Domaine')),
                ('max_students', models.PositiveIntegerField(default=1, verbose_name="Nombre max d'étudiants")),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('completed', 'Terminé')], default='open', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
    ]
